### ISSUE TITLE
Detailansicht in Kitodo.Presentation funktioniert nicht (Kapitel 14)

### ISSUE THREAD

**Issue by felixlohmeier** [kitodo/kitodo-tutorials#1]
Es besteht noch ein Fehler im Zusammenspiel zwischen dem Page View Plugin und dem Introduction Package. Auf der Seite Detailansicht wird leider nichts angezeigt.

**Comment by felixlohmeier** [comment]
Lieber @sebastian-meyer, könntest Du Dir das Problem nochmal anschauen? Das Inline-CSS hat das Problem nicht behoben, das wir in der Videokonferenz vor dem Workshop festgestellt hatten.

**Comment by sebastian-meyer** [comment]
Entgegen meiner ersten Vermutung ist das offenbar kein CSS-, sondern ein jQuery-Problem, das auf die Umstellung von `t3jquery` auf die TYPO3-eigene jQuery-Bibliothek zurückzuführen ist. Ich habe einen entsprechendes Issue für Kitodo.Presentation aufgemacht: https://github.com/kitodo/kitodo-presentation/issues/304

**Comment by sebastian-meyer** [comment]
Das Problem ist für mich nicht reproduzierbar. Unter TYPO3 8.7 und mit dem aktuellen master-Branch funktioniert das Plugin ohne weitere Konfiguration.
